/*
	UIZE JAVASCRIPT FRAMEWORK

	http://www.uize.com/reference/Uize.Build.Util.html
	Available under MIT License or GNU General Public License -- http://www.uize.com/license.html
*/
Uize.module({name:'Uize.Build.Util',required:['Uize.Url','Uize.Template','Uize.Data.Simple','Uize.String','Uize.String.Lines','Uize.Json','Uize.Array.Sort','Uize.Services.FileSystem'],builder:function(){'use strict';var _a;var _b=Uize.Services.FileSystem.singleton(),_c={},_d,_e=/(\.js|\.js\.jst|\.csst)$/;function _f(_g,_h){return(_h?_g.replace(_e,''):_g).replace(/[\/_]/g,'.');}return _d={jsModuleExtensionRegExp:_e,moduleNameFromModulePath:_f,getPathToRoot:function(_i){return Uize.String.repeat('../',_i.length-_i.replace(/[\/\\]/g,'').length);},getTitleFromFilename:function(_j){return _j.match(/(.*)\.[^\.]*$/)[1].replace(/-/g,' ');},getHtmlFileInfo:function(_k,_l){var _m=_b.readFile({path:_k}),_n=_m.match(/<meta name="keywords" content="(.*?)"\/>/),_o=_m.match(/<meta name="description" content="(.*?)"\/>/),_p=_m.match(/<link rel="image_src" href="(.*?)"\/>/);return{path:_k,title:_l(_m.match(/<title>(.*?)<\/title>/)[1]),keywords:_n?_n[1]:'',description:_o?_o[1]:'',imageSrc:_p?Uize.Url.toAbsolute(_q,_p[1]):''};
},getHtmlFilesInfo:function(_q,_l){if(!_l)_l=Uize.returnX;return Uize.Array.Sort.sortBy(Uize.map(_b.getFiles({path:_q,pathMatcher:function(_i){var _r=Uize.Url.from(_i);return _r.fileType=='html'&& !Uize.String.startsWith(_r.file,'~');}}),function(_i){return _d.getHtmlFileInfo(_q+'/'+Uize.Url.from(_i).file,_l);}),'value.title.toLowerCase ()');},getTestModuleName:function(_s){return _s.match(/([^\.]*)(\.|$)/)[1]+'.Test.'+_s;},getJsModules:function(_t){var _u=_t.sourcePath+'/'+_t.modulesFolder,_v={},_w={},_s,_x=_b.getFiles({path:_u,recursive:true,pathMatcher:_e,pathTransformer:function(_k){_w[_s=_f(_k,true)]=_v;return _s;}});_b.getFolders({path:_u,recursive:true,pathTransformer:function(_k){if(_w[_s=_f(_k)]!=_v)_x.push(_s);}});return _x.sort();},readSimpleDataFile:function(_y){return Uize.Data.Simple.parse({simple:_b.readFile({path:_y}),collapseChildren:true});},compileJstFile:function(_z){var _A=_c[_z];if(!_A){if(!_b.fileExists({path:_z}))return;_A=_c[_z]=Uize.Template.compile(_b.readFile({path:_z}),
{result:'full'});Uize.require(_A.required);}return _A.templateFunction;},processJstFile:function(_z,_B){var _A=_d.compileJstFile(_z);_A&&_b.writeFile({path:_z.replace(/\.jst$/,''),contents:_A(_B)});},exec:function(_C){var _D;if(!Uize.isArray(_C))_C=[_C];for(var _E= -1,_F=_C.length,_G=new ActiveXObject('WScript.Shell'),_H;++_E<_F&& !_D;)if(_H=_G.Run(_C[_E],0,true))_D={script:_C[_E],errorCode:_H};return _D;},runScripts:function(_I){return _d.exec(Uize.map(Uize.isArray(_I)?_I:[_I],'\'WScript \' + value'));},runUnitTests:function(_J,_K,_L){function _M(_J){var _N=new _J,_O=[];_N.wire({Start:function(_P){_O.push(Uize.String.repeat('\t',_P.source.getDepth())+_P.source.get('title'));},Done:function(_P){var _Q=_P.source,_R=_Q.get('reasonForFailure');_O.push(Uize.String.repeat('\t',_Q.getDepth()+1)+(_Q.get('result')?('PASSED!!! (duration: '+_Q.get('duration')+'ms)'):('*** FAILED *** '+(_R||''))));_R&&_O.push('','',_Q.getSynopsis());if(_Q==_N|| !_Q.get('result')){_K||alert(_Q.getSynopsis());_L&&
_b.writeFile({path:_L,contents:_O.join('\n')});_Q.get('result')||WScript.Quit(1);}}});_N.run();}typeof _J=='string'?Uize.require(_J,_M):_M(_J);},moduleAsText:function(_S){var _T=_S.builder,_U=typeof _T=='string',_V='[BUILDER_PLACEHOLDER_'+Uize.now()+']';if(_U)_S.builder=_V;var _W='Uize.module ('+Uize.Json.to(_S)+');';if(_U){var _X=_W.indexOf(_V);_W=_W.slice(0,_X-1)+Uize.String.Lines.indent(_T,1,'\t',false)+_W.slice(_X+_V.length+1);}return _W;},dataAsModule:function(_s,_Y){return _d.moduleAsText({name:_s,builder:['function () {','	return function () {','		return '+Uize.String.Lines.indent(Uize.Json.to(_Y),2,'\t',false)+';','	};','}'].join('\n')});},writeDataModule:function(_Z,_s,_Y){_b.writeFile({path:_Z+'/'+_s+'.js',contents:_d.dataAsModule(_s,_Y)});},buildFiles:function(_t){var _0=_t.alwaysBuild,_1=_t.dryRun,_2=_t.doNotEnter,_L=_t.logFilePath,_O=[];if(Uize.isArray(_2))_2=new RegExp('^('+_2.join('|')+')$');function _3(_4){var _5=_2&&_2.test(_4)?false:_t.targetFolderPathCreator(_4);if(typeof _5=='string'){
Uize.forEach(_b.getFiles({path:_4}),function(_6){var _7=_4+(_4&&'/')+_6,_8=_t.targetFilenameCreator(_6);if(_8){var _9=_5+'/'+_8,_ba=_0?'ALWAYS BUILD':(_b.fileExists({path:_9})?(_b.getModifiedDate({path:_7})>_b.getModifiedDate({path:_9})?'WAS OUT OF DATE':''):'DIDN\'T EXIST'),_bb,_bc='';if(_ba){var _bd=Uize.now(),_be=_t.fileBuilder(_6,_b.readFile({path:_7})),_bf=_be.outputText;_bc=_be.logDetails||'';!_1&&_bf!=_a&&_b.writeFile({path:_9,contents:_bf});_bb=Uize.now()-_bd;}_O.push((_ba?'***** ':'')+_7+'\n'+'\tTARGET FILE: '+_9+'\n'+'\t'+(_ba?('BUILT ('+_ba+'), BUILD DURATION: '+_bb+'ms'):'no action, file is current')+'\n'+_bc+'\n');}});}_5!==false&&Uize.forEach(_b.getFolders({path:_4}),function(_bg){_3(_4+(_4&&'/')+_bg)});}_3(_t.rootFolderPath);_L&&_b.writeFile({path:_L,contents:_O.join('')});}};}});