/*
	UIZE JAVASCRIPT FRAMEWORK

	http://www.uize.com/reference/Uize.Widget.Dialog.html
	Available under MIT License or GNU General Public License -- http://www.uize.com/license.html
*/
Uize.module({name:'Uize.Widget.Dialog',superclass:'Uize.Widget.V2',required:['Uize.Node','Uize.Widget.Button','Uize.Widget.Drag','Uize.Fade'],builder:function(d_a){'use strict';var d_b=true,d_c=false,d_d,d_e=Uize.Node,d_f=Uize.Widget,d_g=d_f.Drag;var d_h={},d_i={},d_j=0,d_k=d_e.ieMajorVersion==6;var d_l=d_a.subclass(function(){var d_m=this;(d_m.d_n=d_m.shieldFade=Uize.Fade({curve:Uize.Fade.celeration(0,1),duration:750})).wire('Changed.value',function(){d_m.set({d_o:+d_m.d_n})});d_m.wire({'Drag Start':function(d_p){if(!d_m.d_q){d_m.d_q=d_b;d_m.fire('First Drag Since Shown');d_m.d_r&&d_m.set({d_s:d_c});}},'Drag Done':function(){var d_t=d_e.getById(d_m.d_t);if(d_t){var d_u=d_e.getCoords(d_t),d_v=d_m.getNode();d_m.set({offsetX:parseInt(d_e.getStyle(d_v,'left'))-d_u.left,offsetY:parseInt(d_e.getStyle(d_v,'top'))-d_u.top})}}});},function(){var d_m=this;var d_v,d_w=[0,0];(d_m.d_x=d_m.addChild('drag',d_g,{cursor:'move'})).wire({'Before Drag Start':function(d_p){d_v=d_m.getNode();
d_w[0]=parseInt(d_e.getStyle(d_v,'left'));d_w[1]=parseInt(d_e.getStyle(d_v,'top'));},'Changed.inDrag':function(){d_m.set({d_y:d_m.d_x.get('inDrag')})},'Drag Start':d_m,'Drag Update':function(d_p){var d_z=d_m.d_x.eventDeltaPos;d_e.setStyle(d_v,{left:d_w[0]+d_z[0],top:d_w[1]+d_z[1]});},'Drag Done':d_m});function d_A(d_B){d_m.d_A(d_B)}d_m.d_C('close',function(){d_A('Close')});d_m.d_C('qualifiedOk',function(){d_A('Qualified Ok')});d_m.d_C('ok',function(){d_A('Ok')});d_m.d_C('cancel',function(){d_A('Cancel')});d_m.d_D();d_m.atEndOfOmegaStructor();}),d_E=d_l.prototype;d_E.d_C=function(d_F,d_G){var d_H=this.addChild(d_F,this.Class.buttonWidgetClass);d_H.wire('Click',d_G);return d_H;};d_E.d_A=function(d_B){this.fire(d_B).abort||this.set({d_I:d_c})};var d_J=d_E.d_J=d_E.updateUiPositionIfShown=function(){var d_m=this;if(d_m.isWired&&d_m.d_I&& !d_m.d_y){d_g.resizeShield(d_m.getNode('shield'));if(d_m.d_K){var d_v=d_m.getNode(),d_t=d_e.getById(d_m.d_t),d_L=d_m.d_L,d_M=d_m.d_M;if(!d_t||d_L==d_d||d_M==d_d)
d_e.centerInWindow(d_v);if(d_t){if(d_L=='adjacent'||d_M=='adjacent'){d_e.setAbsPosAdjacentTo(d_v,d_t);}else{var d_u=d_e.getCoords(d_t);d_e.setStyle(d_v,Uize.copy(d_L!=d_d?{left:d_u.left+d_L}:d_d,d_M!=d_d?{top:d_u.top+d_M}:d_d));}}}}};var d_N=d_E.d_N=function(){var d_m=this;d_m.isWired&&d_m.d_I&& !d_m.d_y&&d_m.setNodeStyle('',{width:d_m.d_O,height:d_m.d_P});};d_E.d_Q=function(){var d_m=this;d_m.isWired&&d_m.d_I&&d_m.setNodeOpacity('shield',d_m.d_o);};d_E.d_R=function(){var d_m=this;if(d_m.isWired){var d_S=d_m.d_T||d_m.d_U;d_S!=d_d&&d_m.setNodeInnerHtml('title',d_S||'&nbsp;');}};var d_D=d_E.d_D=function(){var d_m=this,d_V=d_m.children;function d_W(d_X,d_Y){d_X&&d_Y!=d_d&&d_X.set({text:d_Y});}d_W(d_V.ok,d_m.d_Z||d_m.d_0);d_W(d_V.cancel,d_m.d_1||d_m.d_2);};d_E.atEndOfOmegaStructor=d_E.afterWireUi=Uize.nop;d_E.updateUi=function(){var d_m=this;if(d_m.isWired){d_m.d_R();d_a.doMy(d_m,'updateUi');}};d_E.wireUi=function(){var d_m=this;if(!d_m.isWired){d_m.wireNode(window,'resize',function(){d_m.d_J()});
d_m.d_x.set({node:d_m.getNode('title')});d_m.wireNode('shield','click',function(){d_m.d_3&&d_m.d_A('Close')});var d_4=function(d_5,d_X,d_6){if(!d_m.get(d_5)){var d_7=(d_X.getNode(d_6)||d_h).innerHTML;d_7&&d_m.set(d_5,d_7);}};d_4('defaultTitle',d_m,'title');d_4('defaultOkText',d_m.children.ok,'text');d_4('defaultCancelText',d_m.children.cancel,'text');d_a.doMy(d_m,'wireUi');d_m.afterWireUi();}};d_l.stateProperties({d_K:{name:'autoPosition',value:d_b,onChange:d_J},d_1:{name:'cancelText',onChange:d_D},d_o:{name:'currentShieldOpacity',onChange:d_E.d_Q},d_2:{name:'defaultCancelText',onChange:d_D},d_0:{name:'defaultOkText',onChange:d_D},d_U:{name:'defaultTitle',onChange:d_E.d_R},d_3:{name:'dismissOnShieldClick',value:d_c},d_P:{name:'height',onChange:[d_N,d_J]},d_r:{name:'hideShieldOnDrag',value:d_b},d_y:{name:'inDrag',value:d_c},d_t:{name:'mooringNode',onChange:d_J},d_L:{name:'offsetX',onChange:d_J,value:0},d_M:{name:'offsetY',onChange:d_J,value:0},d_8:{name:'okEnabledOnShow',value:d_b},d_Z:{name:'okText',
onChange:d_D},d_9:{name:'shieldOpacity',onChange:function(){this.d_s&&this.set({d_o:this.d_9})},value:.3},d_s:{name:'shieldShown',onChange:function(){var d_m=this;if(d_m.isWired&&d_m.d_I){if(d_m.d_s){if(d_k&&d_m.getNode('shield')){var d_ba=d_m.getNode('ie6SelectHackShield');if(!d_m.d_3&& !d_m.getNode('ie6SelectHackShield')){d_m.flushNodeCache('ie6SelectHackShield');d_m.injectNodeHtml('shield','<iframe src="javascript:\'\'" id="'+d_m.d_bb+'-ie6SelectHackShield" style="position:absolute; left:0; top:0; width:100%; height:100%; filter:alpha(opacity=0);" frameborder="0" scrolling="no"></iframe>','inner bottom');}}d_m.d_o=d_d;d_m.set({d_o:d_m.d_9});}else{d_m.d_n.start({startValue:d_m.d_9,endValue:.001});}}},value:d_c},d_I:{name:'shown',onChange:function(){var d_m=this;if(d_m.isWired){if(d_m.d_I){d_j++;d_m.d_q=d_c;typeof d_m.d_8=='boolean'&&d_m.children.ok.set({enabled:d_m.d_8?'inherit':d_c});d_m.fire('Before Show');d_m.setNodeStyle('',{position:'absolute'});var d_bc= -1;for(var d_bd in d_i)d_bc=Math.max(d_bc,d_bd)
;d_i[d_m.d_bd= ++d_bc]=1;d_m.setNodeStyle(['','shield'],{zIndex:4000+d_bc*10});var d_be=function(d_bf){d_m.showNode('',!d_bf);d_m.displayNode('',d_bf);};d_be(d_b);d_m.d_N();d_m.d_J();d_be(d_c);}else{d_j--;delete d_i[d_m.d_bd];d_m.fire('Before Hide');}d_m.set({d_s:d_m.d_I});d_m.displayNode(['','shield'],d_m.d_I);d_m.fire(d_m.d_I?'After Show':'After Hide');}},value:d_c},d_T:{name:'title',onChange:d_E.d_R},d_O:{name:'width',onChange:[d_N,d_J]}});d_l.staticProperties({buttonWidgetClass:Uize.Widget.Button,enableRootNodeCssClasses:false});return d_l;}});