/*
	UIZE JAVASCRIPT FRAMEWORK

	http://www.uize.com/reference/Uize.Service.html
	Available under MIT License or GNU General Public License -- http://www.uize.com/license.html
*/
Uize.module({name:'Uize.Service',superclass:'Uize.Class',builder:function(b_a){var b_b,b_c=false,b_d=true,b_e=Uize,b_f=5000;var b_g=b_a.subclass(),b_h=b_g.prototype;function b_i(b_j){typeof console!='undefined'&&typeof console.log=='function'&&console.log(b_j);}function b_k(b_l,b_m){return function(){return b_l[b_m].apply(b_l,arguments)};}b_g.b_n={};b_h.b_o=function(b_j){b_i('SERVICE WARNING: '+b_j);};b_g.serviceMethods=b_g.declareServiceMethods=function(b_n){var b_l=this,b_p=b_l.b_n,b_q={};function b_r(b_m,b_s){var b_t=b_m=='init';function b_u(b_j){return'<< '+b_m+' >> '+b_j}if(b_l.prototype[b_m])throw new Error(b_u('You may not override a non-service public method with a service method'));b_p[b_m]=b_s||(b_s={});b_s.async=b_s.async!==b_c;b_q[b_m]=function(b_v,b_w){var b_l=this,b_x=b_l.get('adapter'),b_y=b_s.async;if(!b_y){if(!b_x)throw new Error(b_u('To call a synchronous service method, a service adapter must be set and the service must be initialized'));if(!b_t&& !b_l.get('initialized'))throw new Error(
b_u('In order to call a synchronous service method, the service must already be initialized'));}if(b_v==b_b){b_v={};}else if(typeof b_v!='object'){throw new Error(b_u('First argument (params) must be an object, null, or undefined'));}var b_z=b_c,b_A,b_B,b_C,b_D,b_E,b_F=function(){b_C&&clearTimeout(b_C);function b_G(){var b_H,b_I;if(b_w){var b_J=typeof b_w;if(b_J=='function'){b_H=b_w;}else if(b_J=='object'){b_H=b_w.onSuccess;b_I=b_w.onError;}}if(b_E){if(b_I){b_I(b_E);}else{typeof b_E=='string'?(b_E=new Error(b_u(b_E))):(b_E.message=b_u(b_E.message));throw b_E;}}else{b_t&&b_l.set('initialized',b_d);b_H&&b_H(b_D);}}if(b_B!==b_b){throw new Error(b_u('Service adapter method should only return once'));}else{b_B=Uize.now();var b_K=b_B-b_A;b_K>b_f&&b_l.b_o(b_u('Service adapter method took too long to return ('+b_K+'ms)'));if(b_s.async){b_z?b_G():setTimeout(b_G,0);}else{if(b_z){throw new Error(b_u('Service method is declared as synchronous, but implementation in adapter is asynchronous'));}else{b_G();}}}},
b_L=function(){if(b_x[b_m](b_v,function(b_M){b_D=b_M;b_F();},function(b_N){b_E=b_N||{};b_F();})!==b_b)throw new Error(b_u('Service adapter method should always provide its result through a callback, not a return statement'));b_z=b_d;};b_A=Uize.now();if(b_y)b_C=setTimeout(function(){var b_O=b_l.get('initialized');b_l.b_o(b_u(b_x&&b_O?'Service adapter method taking too long to return':('Taking too long to be ready to call service adapter method ('+'adapter '+(b_x?'':'not ')+'set, '+(b_O?'':'not ')+'initialized'+')')));},b_f);if(b_t){b_v.serviceInterface={fire:b_k(b_l,'fire'),wire:b_k(b_l,'wire'),set:b_k(b_l,'set'),get:b_k(b_l,'get')};b_v.service=b_l;b_l.once('adapter',b_L);}else{if(!b_x){b_l.b_o(b_u('Adapter is not yet set when service method is called'));}else if(!b_l.get('initialized')){b_l.b_o(b_u('Service adapter is set but not yet initialized when service method is called'));}b_l.once('adapter',function(){b_x=b_l.get('adapter');b_l.once('initialized',b_L);});}return b_D;};}
if(arguments.length!=1||typeof b_n!='object')b_n=[].slice.call(arguments);Uize.forEach(b_n,Uize.isArray(b_n)?function(b_m){b_r(b_m)}:function(b_s,b_m){b_r(b_m,b_s)});Uize.copyInto(b_l.prototype,b_q);};b_g.stateProperties({b_x:{name:'adapter',conformer:function(b_x){if(typeof b_x=='string'){var b_P=Uize.getModuleByName(b_x);if(b_P){b_x=new b_P;}else{throw new Error('The adapter module '+b_x+' must be required and loaded first if you wish to set an adapter by module name');}}if(b_x!=b_b){var b_Q=[];Uize.forEach(this.constructor.b_n,function(b_R,b_S){typeof b_x[b_S]!='function'&&b_Q.push(b_S);});if(b_Q.length){b_x=b_b;throw new Error('Service module adapter is missing implementations for service methods: '+b_Q.sort().join(', '));}}return b_x;},onChange:function(){this.set({initialized:b_c})}},b_O:{name:'initialized',value:b_c}});return b_g;}});