/*
	UIZE JAVASCRIPT FRAMEWORK

	http://www.uize.com/reference/Uize.Test.Performance.TestingForUndefined.html
	Available under MIT License or GNU General Public License -- http://www.uize.com/license.html
*/
Uize.module({name:'Uize.Test.Performance.TestingForUndefined',builder:function(){'use strict';var c_a=500000,c_b,c_c='this is a string value',c_d='undefined',c_e;return Uize.Test.declare({title:'Test the performance of different approaches to testing for an undefined value',test:[{title:'typeof myVariable == undefinedStr',test:[{title:'When the variable being tested is undefined',test:function(){for(var c_f=c_a;--c_f>=0;){typeof c_b==c_d;typeof c_b==c_d;typeof c_b==c_d;typeof c_b==c_d;typeof c_b==c_d;typeof c_b==c_d;typeof c_b==c_d;typeof c_b==c_d;typeof c_b==c_d;typeof c_b==c_d;typeof c_b==c_d;typeof c_b==c_d;typeof c_b==c_d;typeof c_b==c_d;typeof c_b==c_d;typeof c_b==c_d;typeof c_b==c_d;typeof c_b==c_d;typeof c_b==c_d;typeof c_b==c_d;}return true;}},{title:'When the variable being tested is not undefined',test:function(){for(var c_f=c_a;--c_f>=0;){typeof c_c==c_d;typeof c_c==c_d;typeof c_c==c_d;typeof c_c==c_d;typeof c_c==c_d;typeof c_c==c_d;typeof c_c==c_d;typeof c_c==c_d;typeof c_c==c_d;typeof c_c==c_d;
typeof c_c==c_d;typeof c_c==c_d;typeof c_c==c_d;typeof c_c==c_d;typeof c_c==c_d;typeof c_c==c_d;typeof c_c==c_d;typeof c_c==c_d;typeof c_c==c_d;typeof c_c==c_d;}return true;}}]},{title:'typeof myVariable == \'undefined\'',test:[{title:'When the variable being tested is undefined',test:function(){for(var c_f=c_a;--c_f>=0;){typeof c_b=='undefined';typeof c_b=='undefined';typeof c_b=='undefined';typeof c_b=='undefined';typeof c_b=='undefined';typeof c_b=='undefined';typeof c_b=='undefined';typeof c_b=='undefined';typeof c_b=='undefined';typeof c_b=='undefined';typeof c_b=='undefined';typeof c_b=='undefined';typeof c_b=='undefined';typeof c_b=='undefined';typeof c_b=='undefined';typeof c_b=='undefined';typeof c_b=='undefined';typeof c_b=='undefined';typeof c_b=='undefined';typeof c_b=='undefined';}return true;}},{title:'When the variable being tested is not undefined',test:function(){for(var c_f=c_a;--c_f>=0;){typeof c_c=='undefined';typeof c_c=='undefined';typeof c_c=='undefined';typeof c_c=='undefined';
typeof c_c=='undefined';typeof c_c=='undefined';typeof c_c=='undefined';typeof c_c=='undefined';typeof c_c=='undefined';typeof c_c=='undefined';typeof c_c=='undefined';typeof c_c=='undefined';typeof c_c=='undefined';typeof c_c=='undefined';typeof c_c=='undefined';typeof c_c=='undefined';typeof c_c=='undefined';typeof c_c=='undefined';typeof c_c=='undefined';typeof c_c=='undefined';}return true;}}]},{title:'myVariable === variableDeliberatelyNotDefined',test:[{title:'When the variable being tested is undefined',test:function(){for(var c_f=c_a;--c_f>=0;){c_b===c_e;c_b===c_e;c_b===c_e;c_b===c_e;c_b===c_e;c_b===c_e;c_b===c_e;c_b===c_e;c_b===c_e;c_b===c_e;c_b===c_e;c_b===c_e;c_b===c_e;c_b===c_e;c_b===c_e;c_b===c_e;c_b===c_e;c_b===c_e;c_b===c_e;c_b===c_e;}return true;}},{title:'When the variable being tested is not undefined',test:function(){for(var c_f=c_a;--c_f>=0;){c_c===c_e;c_c===c_e;c_c===c_e;c_c===c_e;c_c===c_e;c_c===c_e;c_c===c_e;c_c===c_e;c_c===c_e;c_c===c_e;c_c===c_e;c_c===c_e;c_c===c_e;c_c===c_e;
c_c===c_e;c_c===c_e;c_c===c_e;c_c===c_e;c_c===c_e;c_c===c_e;}return true;}}]},{title:'myVariable === undefined',test:[{title:'When the variable being tested is undefined',test:function(){for(var c_f=c_a;--c_f>=0;){c_b===undefined;c_b===undefined;c_b===undefined;c_b===undefined;c_b===undefined;c_b===undefined;c_b===undefined;c_b===undefined;c_b===undefined;c_b===undefined;c_b===undefined;c_b===undefined;c_b===undefined;c_b===undefined;c_b===undefined;c_b===undefined;c_b===undefined;c_b===undefined;c_b===undefined;c_b===undefined;}return true;}},{title:'When the variable being tested is not undefined',test:function(){for(var c_f=c_a;--c_f>=0;){c_c===undefined;c_c===undefined;c_c===undefined;c_c===undefined;c_c===undefined;c_c===undefined;c_c===undefined;c_c===undefined;c_c===undefined;c_c===undefined;c_c===undefined;c_c===undefined;c_c===undefined;c_c===undefined;c_c===undefined;c_c===undefined;c_c===undefined;c_c===undefined;c_c===undefined;c_c===undefined;}return true;}}]}]});}});