/// Assign Data///////////////

componentsArr = new Array( "iUI", "JQueryForIphone", "JQueryMobile", "JQuery", "Mootools", "Dojo", "UIZE", "YUI", "Prototype",  "KineticJS", "ExtJS");
controlsArr = [
    { name: "JQueryForIphone", value: "iToggle,iButton,iPhoneContacts,iPhoneSpringboard,iPhoneUI" },
	{ name: "JQueryMobile", value: "JQueryMobile" },
    { name: "iUI", value: "iUI" },
    { name: "Mootools", value: "Tree,Slider,Accordion,TabPanel,Drop Menu,Dialog,Tooltip,Grid,SpinButton,Autocomplete,Sortable List,Button,Milk Chart,CheckBox,RadioButton,ProgressBar,jsPalette,Eye,Clock,FancyBars" },
    { name: "Dojo", value: "Dojo" },
    { name: "UIZE", value: "Widget" },
    { name: "YUI", value: "Accordion,Editor,TreeView Port,Button CSS,Console,DataGrid,AutoComplete,DatePicker,Rating,Dual Slider" },
    { name: "JQuery", value: "JAccordion,JAutocomplete,JButton,JDatePicker,JDialog,JDraggable,JEffect,JMenu,JPosition,JProgressBar,JResizable,JSelectable,JSlider,JSortable,JSpinner,JTabs,JTooltip,JWidget" },
    { name: "Prototype", value: "Prototype Examples" },
	{ name: "KineticJS", value: "KineticJS CoreShapes,KineticJS Plugins,KineticJS Styling,KineticJS Events,KineticJS Groups and Layers,KineticJS Filter,KineticJS Tweens,KineticJS Animations"},
	{ name: "ExtJS", value: "ExtJS Examples"}];
sampleArr = [
    { name: "Widget", value: "AutoTooltip,Button,Beam,Bevel,Calculator,Calendar,CollectionDynamic,CollectionItemZooming,ColorCube,Dialog,DragMove,DatePicker,ListEitor,MagView,Mask,ImagePort,Page,ProgressBar,Population,Scrolly,Slider,SliderPlus,SliderxSkin,SlideShow,SegmentDisplay,SwapHTML,Table,ToggleButton,Options,ImageWipe,Tabbed,TextInput,TreeList,TreeMenu,TreeSelect" },
	{ name: "KineticJS CoreShapes", value: "Rect,Ciercle,Wedge,Line,Polygon,Image,Sprite,Text,Spline,Blob,Custom"},
	{ name: "KineticJS Plugins", value: "Label,RegularPolyGon,Star,Path,TexPath"},
	{ name: "KineticJS Styling", value: "Fill,Stroke,Opacity,Shadow,LineJoin,HideAndShow"},
	{ name: "KineticJS Events", value: "BindingEvents,ImageEvents,DragAndDrop,DragImage,DragGroup,DragLine,DragStage,DragBounds" },
    { name: "KineticJS Groups and Layers", value: "Groups,Layering,ChangeContainers,ClippingRegions" },
    { name: "KineticJS Filter", value: "InvertImage,GrayscaleImage,Brighten,Blur" },
    { name: "KineticJS Tweens", value: "Easings,AllEasings" },
    { name: "KineticJS Animations", value: "Moving,Rotating,Scaling" },
    { name: "Prototype Examples", value: "Calendar,CheckBox,ColorPicker,Dialog,RichTextEditor,ShowCase,Spinner,Tabs,TabStrip,TimerPicker,TreeList"},    
	{ name: "ExtJS Examples", value: "ExtJSCombination" },
	{ name: "JAccordion", value: "Accordion" },
	{ name: "JAutocomplete", value: "Autocomplete" },
	{ name: "JButton", value: "Button" },
	{ name: "JDatePicker", value: "DatePicker"},
	{ name: "JDialog", value: "Dialog"},
	{ name: "JDraggable", value: "Draggable"},
	{ name: "JEffect", value: "Effect"},
	{ name: "JMenu", value: "Menu"},
	{ name: "JPosition", value: "Position"},
	{ name: "JProgressBar", value: "ProgressBar"},
	{ name: "JResizable", value: "Resizable"},
	{ name: "JSelectable", value: "Selectable"},
	{ name: "JSlider", value: "Slider"},
	{ name: "JSortable", value: "Sortable"},
	{ name: "JSpinner", value: "Spinner"},
	{ name: "JTabs", value: "Tabs"},
	{ name: "JTooltip", value: "Tooltip"},
	{ name: "JWidget", value: "Widget"},   

    { name: "Option", value: "InputSubmit" },
    { name: "Tree", value: "TreeView,SVGTree" },
    { name: "Slider", value: "Slider" },
    { name: "Accordion", value: "Accordion" },
    { name: "TabPanel", value: "TabPanel" },
    { name: "Grid", value: "Grid" },
    { name: "Drop Menu", value: "DropMenu" },
    { name: "Dialog", value: "Dialog" },
    { name: "SpinButton", value: "SpinButton" },
    { name: "Tooltip", value: "Tooltip" },
    { name: "Autocomplete", value: "Autocomplete" },
    { name: "Button", value: "Button" },
    { name: "CheckBox", value: "CheckBox" },
    { name: "RadioButton", value: "RadioButton" },
    { name: "ProgressBar", value: "ProgressBar" },
    { name: "jsPalette", value: "jsPalette" },
    { name: "Eye", value: "Eye" },
    { name: "Clock", value: "Clock" },
    { name: "FancyBars", value: "FancyBars" },
    { name: "Milk Chart", value: "MilkChart" },
    { name: "Dojo", value: "Dojo" },
    { name: "Accordion", value: "Accordion" },
    { name: "Editor", value: "Editor" },
    { name: "TreeView Port", value: "TreeViewPort" },
    { name: "Button CSS", value: "ButtonCSS" },
    { name: "Console", value: "Console" },
    { name: "DataGrid", value: "DataGrid" },
    { name: "AutoComplete", value: "AutoComplete" },
    { name: "DatePicker", value: "DatePicker" },
    { name: "Rating", value: "Rating" },
    { name: "Dual Slider", value: "DualSlider" },
    { name: "Sortable List", value: "SortableList" },
    { name: "iUI", value: "iUI" },
    { name: "iToggle", value: "iToggle" },
    { name: "iButton", value: "iButton" },
    { name: "iPhoneContacts", value: "iPhoneContacts" },
    { name: "iPhoneSpringboard", value: "iPhoneSpringboard" },
    { name: "iPhoneUI", value: "iPhoneUI" },
	{ name: "JQueryMobile", value: "JQueryMobile" }
];
////////////////////////////////////////////////
