/*
	UIZE Web Site

	http://www.uize.com/reference/UizeSite.SiteMap.html
	Available under MIT License or GNU General Public License -- http://www.uize.com/license.html
*/
Uize.module({name:'UizeSite.SiteMap',required:['UizeSite.ModulesTree','UizeSite.ExamplesInfoForSiteMap'],builder:function(){'use strict';var _a;return function(_b){if(!_a||_b){if(!_b)_b={};var _c={title:'-'};var _d=function(_e,_f,_g){var _h=_e+(_e&&'.')+_f,_i='reference/'+_h+'.html',_j={title:_f,link:_i},_k=_j.items=[];if(_g)for(var _l in _g)_k.push(_d(_h,_l,_g[_l]));_k.length&&_h&&_k.unshift({title:'[[ BASE ]]',link:_i},_c);return _j;},_m=_d('','',_b.modulesTree||UizeSite.ModulesTree());_m.title='Module Reference';_m.link='javascript-modules-index.html';var _j=function(_n,_o,_p){return{title:_n,link:(_o||'')+(_p||_n.toLowerCase().replace(/\W+/g,'-'))+'.html'}},_q=function(_n,_p){return _j(_n,'explainers/',_p)},_r=function(_s){return _j(_s+' News','','news-'+_s)},_t=function(_n,_p){return _j(_n,'javascript-reference/',_p)},_u=function(_n,_p){return _j(_n,'appendixes/',_p)},_v=function(_n,_p){return _j(_n,'todo/',_p)},_w=function(_n,_p){return _j(_n,'tests/performance/',_p)};
var _x=_b.examplesInfo||UizeSite.ExamplesInfoForSiteMap();var _y=function(_z){var _A='javascript-'+(_z!='all'?(_z+'-'):'')+'examples.html';return{title:Uize.capFirstChar(_z)+' examples',link:_A,items:[{title:'TOUR '+_z.toUpperCase()+' EXAMPLES',link:'javascript-feature-tours.html?tour='+_z},_c,{title:'Index of '+_z+' examples',link:_A}]}},_B=[_y('featured'),_c];Uize.forEach(_x.keywords,function(_C){_C!='featured'&&_B.push(_y(_C));});_B.push(_c,_y('all'),_c,{title:'EXAMPLES, BY MODULE...',link:'javascript-examples-by-module.html'});_a=[_j('Home','','index'),_j('DOWNLOAD'),_q('Getting Started'),{title:'Latest News',link:'latest-news.html',items:[_r(2013),_r(2012),_r(2011),_r(2010),_r(2009),_r(2008),_r(2006)]},_c,{title:'Examples',link:'javascript-examples.html',items:_B},_u('Showcase'),{title:'Widgets To Go',link:'javascript-widgets.html'},{title:'Tools',link:'javascript-tool-examples.html',items:[_j('The DELVE Tool','','explainers/using-the-delve-tool'),_q('JavaScript Bookmarklets'),_c].concat(Uize.map(
_x.tools,function(_D){return{title:_D.title,link:_D.path}}),[_c,_j('Index of JavaScript Tools','','javascript-tool-examples')])},_c,{title:'Explainers',link:'javascript-explainers.html',items:[_q('Introduction to UIZE'),_q('Getting Started With UIZE','getting-started'),_q('Using the Documentation'),_q('Overview of Features'),_q('Building UIZE-powered Pages'),{title:'MORE TOPICS...',items:[_q('JavaScript Modules'),_q('JavaScript Inheritance'),_q('State Properties'),_q('JavaScript Event System'),_c,_q('JavaScript DOM Events'),_q('JavaScript Widgets'),_q('JavaScript Localization'),_q('JavaScript Templates'),_q('JavaScript Animation and Effects'),_c,_q('JavaScript Libraries'),_q('JavaScript Build Scripts'),_q('JavaScript Testing Framework'),_q('JavaScript Documentation System'),_q('All About Scrunching'),_q('JavaScript Strict Mode'),_q('JavaScript Troubleshooting'),_q('Using the DELVE Tool'),_c,_q('General Constructs'),_q('JavaScript Bookmarklets'),_q('The Philosophy of UIZE','philosophy-of-uize')]},_c,
_j('Index of JavaScript Explainers','','javascript-explainers')]},_m,{title:'JavaScript Reference',link:'javascript-reference.html',items:[_t('Array'),_t('Boolean'),_t('Date'),_t('Function'),_t('Math'),_t('Number'),_t('Object'),_t('RegExp'),_t('String'),_t('Window'),_t('XMLHTTPRequest')]},{title:'Appendixes',link:'appendixes.html',items:[_u('Press Center'),_u('Showcase'),_j('License'),_c,_u('Credits'),_j('Endorsements'),_c,_u('HTML Style Guide'),_u('JavaScript Code Conventions'),_u('JavaScript Optimization'),_c,_j('Index of JavaScript Modules','','javascript-modules-index'),_u('SOTU (State of the UIZE)','sotu'),_c,_u('JavaScript Fun'),_u('JavaScript Interview Questions'),_u('Glossary')]},_c,{title:'UIZE Development',items:[_q('Creating a New UIZE Module'),_q('Creating a New UIZE Example Page'),_c,_j('UIZE Unit Tests','examples/'),_j('Widget Visual Tests','examples/'),_j('Widget Visual Samplers','examples/'),{title:'Performance Tests',items:[_w('Caching Node References'),_w('Extended String Class'),
_w('getElementById vs getElementsByName','getElementById-vs-getElementsByName'),_w('Repeat String Approaches'),_w('Storing Length for Iterator'),_w('Storing Reference to Sub-object','storing-reference-to-subobject'),_w('String Concatenation Approaches'),_w('String Match Conditional Styles'),_w('String Starts With Substring Styles')]},_c,_u('SOTU (State of the UIZE)','sotu'),{title:'TO DO',items:[_v('Modules'),_v('Documentation'),_v('General'),_v('News Announcements'),_v('External Site Integration')]}]},_c,_j('SUPPORT'),_j('SITE MAP','','directory'),_j('SEARCH','','search-sections')];}return _a;};}});