/*
	UIZE Web Site

	http://www.uize.com/reference/UizeSite.Templates.ListingsPage.html
	Available under MIT License or GNU General Public License -- http://www.uize.com/license.html
*/
Uize.module({name:'UizeSite.Templates.ListingsPage',required:['Uize.String.Lines','Uize.Xml'],builder:function(){'use strict';var _a=function(){};_a.process=function(input){var output=[];
output.push('<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html xmlns="http://www.w3.org/1999/xhtml">\n<head>\n	<title>',input.title,' | UIZE JavaScript Framework</title>\n	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>\n	<meta name="keywords" content="UIZE JavaScript Framework"/>\n	<meta name="description" content="',Uize.Xml.toAttributeValue(input.metaDescription),'"/>\n	<link rel="alternate" type="application/rss+xml" title="UIZE JavaScript Framework - Latest News" href="http://www.uize.com/latest-news.rss"/>\n	<link rel="stylesheet" href="',input.pathToRoot,'css/page.css"/>\n	<link rel="stylesheet" href="',input.pathToRoot,'css/page.simpledoc.css"/>\n	<link rel="stylesheet" href="',input.pathToRoot,'css/page.listings.css"/>\n</head>\n\n<body>\n\n<script type="text/javascript" src="',input.pathToRoot,'js/Uize.js"></script>\n\n<h1 class="document-title">\n	<a id="page-homeLink" href="',input.pathToRoot,'index.html" title="UIZE JavaScript Framework home"></a>\n	',input.displayTitle||input.title,'\n</h1>\n\n<div class="main">\n\n<div class="preamble">',input.preamble,'</div>\n');
for(var listingNo= -1,listings=input.listings,listingsLength=listings.length,imageFolder=input.imageFolder||input.title.toLowerCase();++listingNo<listingsLength;){var listing=listings[listingNo],listingName=listing.fullName,listingSubTitle=listing.subTitle||'',listingNamePlusSubTitle=listingName+(listingSubTitle&&' - ')+listingSubTitle,moreInfoLink=listing.link;output.push('\n<div class="heading1">',listingNamePlusSubTitle,'</div>\n<div class="infoRow">\n	');if(moreInfoLink){output.push('<a href="',moreInfoLink,'" target="_blank" class="imageLink">');}output.push('<img src="',input.pathToRoot,'images/',imageFolder,'/',listingName.toLowerCase().replace(/ /g,'-'),'.png" alt="',Uize.Xml.toAttributeValue(listingNamePlusSubTitle),'"/>');if(moreInfoLink){output.push('</a>');}for(var lineNo= -1,lines=Uize.String.Lines.split(listing.text),linesLength=lines.length;++lineNo<linesLength;){output.push('\n	<p>',lines[lineNo],'</p>');}if(moreInfoLink){
output.push('\n	<p class="more">more info at... <a href="',moreInfoLink,'" target="_blank">',moreInfoLink,'</a></p>');}output.push('\n	<br class="end"/>\n</div>');}output.push('\n\n</div>\n\n<script type="text/javascript">\n\nUize.module ({\n	required:\'UizeSite.Page.library\',\n	builder:function () {(window.page = UizeSite.Page ()).wireUi ()}\n});\n\n</script>\n\n</body></html>\n');return output.join('');};_a.input={title:'string',displayTitle:'string',pathToRoot:'string',imageFolder:'string',metaDescription:'string',preamble:'string',listings:'array'};return _a;}});