/*
	UIZE JAVASCRIPT FRAMEWORK

	http://www.uize.com/reference/Uize.Services.FileBuilderAdapter.html
	Available under MIT License or GNU General Public License -- http://www.uize.com/license.html
*/
Uize.module({name:'Uize.Services.FileBuilderAdapter',superclass:'Uize.Service.Adapter',required:['Uize.Url','Uize.String','Uize.String.Lines','Uize.Array.Util','Uize.Services.FileSystem','Uize.Json','Uize.Build.Util'],builder:function(c_a){'use strict';var c_b,c_c=Uize.String.startsWith,c_d={},c_e={};function c_f(c_g){c_g+='Path';return function(c_h){return c_c(c_h,this.params[c_g]+'/')};}function c_i(c_j,c_k){var c_l=c_k=='source';c_j+='Path';c_k+='Path';return(c_l?function(c_h){var c_m=this.params,c_n=c_h.slice(c_m[c_j].length);return((c_c(c_n,'/'+c_m.modulesFolder+'/Uize')?c_m.uizePath:c_m[c_k])+c_n);}:function(c_h){var c_m=this.params;return c_m[c_k]+c_h.slice(c_m[c_j].length);});}function c_o(c_g){c_g+='Path';return function(c_p){return this.params[c_g]+(c_p&&c_p.charCodeAt(0)!=47?'/':'')+c_p;};};function c_q(c_g){c_g+='Path';return function(c_h){return c_h.slice(this.params[c_g].length+1)};}return c_a.subclass({alphastructor:function(){var c_r=this;c_r.c_s={};c_r.c_t={};
c_r.fileSystem=Uize.Services.FileSystem.singleton();c_r.urlHandlers=[];},instanceMethods:{registerFileBuilders:function(c_u){Uize.push(this.urlHandlers,Uize.Array.Util.flatten(arguments,Infinity,true));},isBuiltUrl:c_f('built'),isTempUrl:c_f('temp'),isMemoryUrl:c_f('memory'),isSourceUrl:c_f('source'),sourceUrlFromBuiltUrl:c_i('built','source'),sourceUrlFromTempUrl:c_i('temp','source'),sourceUrlFromMemoryUrl:c_i('memory','source'),tempUrlFromBuiltUrl:c_i('built','temp'),tempUrlFromMemoryUrl:c_i('memory','temp'),tempUrlFromSourceUrl:c_i('source','temp'),memoryUrlFromBuiltUrl:c_i('built','memory'),memoryUrlFromTempUrl:c_i('temp','memory'),memoryUrlFromSourceUrl:c_i('source','memory'),builtUrlFromTempUrl:c_i('temp','built'),builtUrlFromMemoryUrl:c_i('memory','built'),builtUrlFromSourceUrl:c_i('source','built'),builtUrl:c_o('built'),tempUrl:c_o('temp'),memoryUrl:c_o('memory'),sourceUrl:c_o('source'),pathUnderBuiltUrl:c_q('built'),pathUnderTempUrl:c_q('temp'),pathUnderMemoryUrl:c_q('memory'),
pathUnderSourceUrl:c_q('source'),writeFile:function(c_m){var c_r=this,c_p=c_m.path;c_r.isMemoryUrl(c_p)?(c_r.c_t[c_p]={contents:c_m.contents,modifiedDate:new Date}):c_r.fileSystem.writeFile(c_m);},readFile:function(c_m){var c_r=this,c_p=c_m.path;return(c_r.isMemoryUrl(c_p)?(c_r.c_t[c_p]||c_d).contents:c_r.fileSystem.readFile(c_m));},getModifiedDate:function(c_m){var c_r=this,c_p=c_m.path;return(c_r.isMemoryUrl(c_p)?(c_r.c_t[c_p]||c_d).modifiedDate:c_r.fileSystem.getModifiedDate(c_m));},fileExists:function(c_m){var c_r=this,c_p=c_m.path;return(c_r.isMemoryUrl(c_p)? !!c_r.c_t[c_p]:c_r.fileSystem.fileExists(c_m));},folderExists:function(c_m){var c_r=this,c_p=c_m.path;return(c_r.isMemoryUrl(c_p)? !!c_r.c_t[c_p]:c_r.fileSystem.folderExists(c_m));},processSimpleDoc:function(c_v,c_w,c_x,c_y){var c_z=c_w.contentsTreeItems,c_A=c_z[0];return this.readFile({path:c_x})(Uize.copyInto({title:c_v,description:(c_A&&(c_A.description||(c_A.items[0]||{}).description))||'',body:c_w.html},c_y));},
moduleNameFromTempPath:function(c_B){var c_C=this.tempUrl(this.params.modulesFolder+'/');return(c_c(c_B,c_C)?Uize.Build.Util.moduleNameFromModulePath(c_B.slice(c_C.length),true):'');},getModuleUrl:function(c_D,c_E){return(this.params.modulesFolder+'/'+Uize.modulePathResolver(c_D)+(c_E!==false?'.js':''));},buildFile:function(c_m,c_F){var c_r=this;if(c_m.filesModified)c_r.c_s={};var c_s=c_r.c_s,c_G=c_m.staleBefore=Uize.toNumber(c_m.staleBefore,-Infinity),c_H= -1;c_m.isDev=c_m.isDev=='true';c_r.params=c_m;function c_I(c_h){var c_J=Uize.now(),c_K=Uize.String.repeat('\t',++c_H),c_L='';if(c_s[c_h]==c_e){c_L=c_K+'file is considered current: '+c_h+'\n'+c_K+'\tduration: '+(Uize.now()-c_J)+'\n';}else{var c_M=Uize.Url.from(c_h),c_N;for(var c_O= -1,c_P=c_r.urlHandlers,c_Q=c_P.length,c_u;++c_O<c_Q;){if((c_u=c_P[c_O]).urlMatcher.call(c_r,c_M)){c_N=c_u;break;}}if(c_N){var c_R=(c_N.builderInputs||Uize.nop).call(c_r,c_M),c_S=c_N.builder;if(c_R||c_S){var c_p=c_M.pathname,c_T=[],c_U,c_V,c_W=c_G,c_X=function(c_Y){
if(typeof c_Y=='string'){if(c_U=c_I(c_Y))c_T.push(c_U);if((c_V=c_r.getModifiedDate({path:c_Y}))>c_W)c_W=c_V;}else{Uize.forEach(c_Y,c_X);}};c_X(c_R);if(!c_r.fileExists({path:c_p})||c_r.getModifiedDate({path:c_p})<c_W){var c_Z;try{if(c_S){c_r.writeFile({path:c_h,contents:c_S.call(c_r,c_R,c_M)});if(c_r.isMemoryUrl(c_h))c_r.c_t[c_h].modifiedDate=c_W;}else{c_r.fileSystem.copyFile({path:Uize.values(c_R)[0],targetPath:c_h});}c_s[c_h]=c_e;}catch(c_0){c_Z=c_0;}c_L=c_K+(c_Z?'### BUILD FAILED ###':'***** BUILT')+': '+c_h+'\n'+c_K+'\thandler: '+c_N.description+'\n'+c_K+'\tduration: '+(Uize.now()-c_J)+'\n'+Uize.String.Lines.indent('builder inputs: '+Uize.Json.to(c_R,{keyDelimiter:': '}),c_H+1)+'\n'+(c_T.length?'\n'+c_T.join('\n'):'')+(c_Z?c_K+'\nERROR: '+c_Z:'');if(c_Z){console.log(c_Z);typeof console!='undefined'&&typeof console.trace=='function'&&console.trace();throw c_Z;}}else{c_L=c_K+'file is current: '+c_h+'\n'+c_K+'\thandler: '+c_N.description+'\n'+c_K+'\tduration: '+(Uize.now()-c_J)+'\n';c_s[c_h]=c_e;}}}}c_H--;
return c_L;}var c_1=c_r.params.pathPrefix;if(c_1==c_b)c_1=c_r.params.builtPath+'/';var c_h=c_m.url,c_2=[];Uize.isArray(c_h)?Uize.forEach(c_h,function(c_h){c_2.push(c_I(c_1+c_h))}):c_2.push(c_I(c_1+c_h));var c_L=c_2.join('\n');console.log(c_L);c_F&&c_F(c_L);}}});}});