/*
	UIZE JAVASCRIPT FRAMEWORK

	http://www.uize.com/reference/Uize.Widgets.Button.Widget.html
	Available under MIT License or GNU General Public License -- http://www.uize.com/license.html
*/
Uize.module({name:'Uize.Widgets.Button.Widget',superclass:'Uize.Widget.V2',required:['Uize.Widgets.Button.Html','Uize.Widgets.Button.Css'],builder:function(d_a){'use strict';var d_b,d_c=true,d_d=false;var d_e,d_f={},d_g={disabled:16,'':8,over:4,active:2,playing:1},d_h={mouseover:['over','Over'],mouseout:['','Out'],mousedown:['down','Down'],mouseup:['over','Up'],click:['over','Click'],dblclick:['over','Double Click']};function d_i(){var d_j=this;d_j.isWired&&d_j.d_k!=d_b&&d_j.setNodeInnerHtml(d_j.getNode('text')||d_j.getNode(),d_j.d_k);}function d_l(){var d_j=this;d_j.isWired&&d_j.d_m!=d_b&&d_j.setNodeProperties('',{title:d_j.d_m});}function d_n(){var d_j=this;if(d_j.d_o){var d_p=d_j.get('enabledInherited'),d_q=d_j.get('busyInherited'),d_r=(!d_p?16:0)|(!d_j.d_s||d_q?8:0)|(d_j==d_e?4:0)|(d_j.d_s=='down'||d_j.d_t?2:0)|(d_j.d_u?1:0),d_v=d_j.d_w[d_r];if(d_v==d_b){for(var d_x= -1,d_y=d_j.d_y,d_z=d_y.length;++d_x<d_z;){var d_A=d_y[d_x];if(d_r&d_g[d_A]){d_v=d_A;break;}}d_j.d_w[d_r]=d_v;}
d_j.set({d_v:d_j.d_B+(d_v&&('-'+d_v))});if(d_j.isWired&&d_j.d_C&&Uize.Tooltip){var d_D=d_j.d_s=='over'&&d_p&& !d_j.d_t;d_D!=d_j.d_E&&Uize.Tooltip.showTooltip(d_j.d_C,d_j.d_E=d_D);}}}var d_F=d_a.subclass({omegastructor:function(){var d_j=this;d_j.d_o=d_c;function d_G(){d_j.d_H()||d_j.set({d_s:''});d_n.call(d_j);}d_j.wire({'Changed.busyInherited':d_G,'Changed.enabledInherited':d_G});d_n.call(d_j);d_j.onChange(function(tipText,enabledInherited,busyInherited){return tipText==d_b?d_b:enabledInherited&& !busyInherited?tipText:'';},function(d_m){d_j.set({d_m:d_m});});},instanceProperties:{d_E:d_d},instanceMethods:{d_H:function(d_I){var d_j=this;return!!(d_j.get('enabledInherited')&& !d_j.get('busyInherited')&&(d_I|| !d_j.d_t||d_j.d_J||d_j.d_K));},d_L:function(d_M){var d_j=this;if(d_j.isWired){var d_N=d_M.type,d_O=d_N=='click',d_H=d_j.d_H(d_N=='dblclick');if(!d_j.d_P){d_j.d_P=d_c;var d_L=function(d_M){d_j.d_L(d_M)};d_j.wireNode(d_j.d_Q,{mouseout:d_L,mousedown:d_L,mouseup:d_L,dblclick:d_L});}
if(d_O)d_M.cancelBubble=d_c;if(d_H){var d_R=d_h[d_N];d_j.set({d_s:d_R[0]});d_j.fire({name:d_R[1],domEvent:d_M});if(d_O){Uize.isFunction(d_j.d_S)&&d_j.d_S();(d_j.d_t?d_j.d_J:d_j.d_T)&&d_j.set({d_t:!d_j.d_t});}}}},updateUi:function(){if(this.isWired){d_i.call(this);d_l.call(this);}},wireUi:function(){var d_j=this;if(!d_j.isWired){var d_Q=d_j.d_Q=d_j.getNode();if(d_Q){if(d_j.d_U&&d_Q.tagName=='A'&& !d_Q.onclick)d_Q.onclick=Uize.returnTrue;var d_L=function(d_M){d_j.d_L(d_M)};d_j.wireNode(d_Q,{mouseover:d_L,click:d_L});d_a.doMy(d_j,'wireUi');}}}},staticProperties:{cssModule:Uize.Widgets.Button.Css},staticMethods:{addChildButton:function(d_V,d_W){var d_j=this,d_X;function d_Y(){d_X.wire('Click',function(d_Z){if(d_W)typeof d_W=='string'?d_j.fire(d_W):d_W(d_Z);d_j.fire(d_Z);});}if(Uize.isInstance(d_j)){d_X=d_j.children[d_V];if(!d_X){d_X=d_j.addChild(d_V,d_F);d_Y();}}else{d_X=new d_j({idPrefix:d_V,name:d_V,d_U:d_c});d_Y();(window[d_X.instanceId]=d_X).wireUi();}return d_X;}},stateProperties:{d_S:'action',d_K:{
name:'allowClickWhenSelected',onChange:d_n},d_T:'clickToSelect',d_J:{name:'clickToDeselect',onChange:d_n},d_v:{name:'displayState'},d_U:{name:'followLink',value:d_d},d_u:{name:'playing',onChange:d_n,value:d_d},d_t:{name:'selected',onChange:d_n,value:d_d},d_0:{name:'size',value:'medium'},d_s:{name:'state',onChange:[function(){var d_j=this;if(!d_j.d_s){if(d_e==d_j)d_e=d_b;}else if(d_j.d_s=='over'){d_e&&d_e!=d_j&&d_e.set({d_s:''});d_e=d_j;}},d_n],value:''},d_y:{name:'statePrecedence',onChange:[function(){var d_j=this,d_1=d_j.d_y.d_2||(d_j.d_y.d_2=d_j.d_y.join(','));d_j.d_w=d_f[d_1]||(d_f[d_1]={});},d_n],value:['playing','active','disabled','over','']},d_k:{name:'text',onChange:d_i},d_m:{name:'displayedTipText',onChange:d_l},d_3:'tipText',d_C:'tooltip',d_B:{name:'flavor',value:'normal',onChange:d_n}},set:{html:Uize.Widgets.Button.Html},stateToCssBindings:{displayState:'value',busyInherited:['','busy'],size:'value'}});return d_F;}});